// Core product data structure
export interface CoreValues {
  temperatureControl: number;    // 온도 조절/유지 성능 (1-10)
  hygiene: number;               // 위생/세척 편의성 (1-10)
  material: number;              // 소재/안전성 (1-10)
  usability: number;             // 사용 편의성 (1-10)
  portability: number;           // 휴대성 (1-10)
  priceValue: number;            // 가격 대비 가치 (1-10, 높을수록 가성비 좋음)
  durability: number;            // 내구성/A/S (1-10)
  additionalFeatures: number;    // 부가 기능/디자인 (1-10)
}

// Product category
export type ProductCategory =
  | 'milk_powder_port'
  | 'baby_bottle'
  | 'baby_bottle_sterilizer'
  | 'baby_formula_dispenser'
  | 'baby_monitor'
  | 'baby_play_mat'
  | 'car_seat'
  | 'nasal_aspirator'
  | 'thermometer';

// Product interface
export interface Product {
  id: string;                    // 쿠팡 아이디
  title: string;
  brand?: string;                // 브랜드명 (optional)
  price: number;
  reviewCount: number;
  reviewUrl: string;             // 리뷰 페이지 URL
  ranking: number;
  thumbnail: string;
  coreValues: CoreValues;
  averageRating?: number;        // 평균 별점 (optional)
  category: ProductCategory;     // 제품 카테고리
}

// Chat message
export interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
  phase?: 'chat1' | 'chat2';
  isImportanceQuestion?: boolean;  // 중요도 질문 메시지인지 여부
  isConfirmation?: boolean;        // 확인 메시지인지 여부
  details?: string[];              // 속성 디테일 리스트 (토글 형식으로 표시)

  // Priority 플로우 전용 메타데이터
  attributeKey?: keyof CoreValues; // 어떤 속성에 대한 메시지인지
  conversationId?: string;         // 속성별 대화 세션 ID (예: "temperatureControl_1")
  turnNumber?: number;             // 해당 속성 대화에서의 턴 번호 (1~5)
  isTransitionPrompt?: boolean;    // 전환 제안 메시지 여부
  showDetailButton?: boolean;      // '자세히 보기' 버튼 표시 여부
}

// User's importance rating for each attribute
export type ImportanceLevel = '중요하지 않음' | '보통' | '중요함';

// Priority level for new flow
export type PriorityLevel = 'low' | 'medium' | 'high';

export interface AttributeAssessment {
  temperatureControl: ImportanceLevel | null;
  hygiene: ImportanceLevel | null;
  material: ImportanceLevel | null;
  usability: ImportanceLevel | null;
  portability: ImportanceLevel | null;
  priceValue: ImportanceLevel | null;
  durability: ImportanceLevel | null;
  additionalFeatures: ImportanceLevel | null;
}

// Priority settings from new Priority page (6 attributes, excluding priceValue)
export interface PrioritySettings {
  temperatureControl?: PriorityLevel;
  hygiene?: PriorityLevel;
  material?: PriorityLevel;
  usability?: PriorityLevel;
  portability?: PriorityLevel;
  additionalFeatures?: PriorityLevel;
}

// Budget range (can be predefined ranges or custom amount as string)
export type BudgetRange = '0-50000' | '0-100000' | '0-150000' | '150000+' | string;

// Chat conversation for a specific attribute
export interface AttributeConversation {
  attributeKey: keyof CoreValues;
  messages: Array<{
    role: 'user' | 'assistant';
    content: string;
    timestamp: number;
  }>;
}

// User persona generated by AI
export interface UserPersona {
  summary: string;                // 페르소나 요약
  coreValueWeights: CoreValues;   // 가중치 (1-10)
  contextualNeeds: string[];      // 추가 맥락 (예: "쌍둥이", "야간 수유 많음")
  budget?: number;                // 예산 (optional)
}

// Core attribute keys type
export type CoreAttributeKey = keyof CoreValues;

// User context summary for result page display
export interface UserContextSummary {
  priorityAttributes: {
    name: string;                 // 속성명 (한글)
    level: ImportanceLevel;       // 중요도 레벨
    reason: string;               // 중요한 이유 (LLM이 대화에서 추출한 맥락)
  }[];
  additionalContext: string[];    // 추가 맥락 정보 (예: "쌍둥이 육아 중", "야간 수유 빈번")
  budget?: string;                // 예산 (있다면)
}

// Reflection result
export interface ReflectionResult {
  isValid: boolean;
  confidence: number;             // 0-100
  issues: string[];
  suggestedRevisions: {
    field: string;
    currentValue: string | number | boolean | null | undefined;
    suggestedValue: string | number | boolean | null | undefined;
    reason: string;
  }[];
}

// Product evaluation grade
export type EvaluationGrade = '매우 충족' | '충족' | '보통' | '미흡' | '매우 미흡';

// Single attribute evaluation
export interface AttributeEvaluation {
  attribute: keyof CoreValues;
  grade: EvaluationGrade;
  reason: string;
}

// Product evaluation by AI
export interface ProductEvaluation {
  productId: string;
  evaluations: AttributeEvaluation[];
  overallScore: 1 | 2 | 3 | 4 | 5;  // 전체적인 평가 점수 (1: 매우 미흡 ~ 5: 매우 충족)
}

// Validation result for evaluations
export interface ValidationResult {
  productId: string;
  isValid: boolean;
  invalidEvaluations: {
    attribute: string;
    issue: string;
    suggestedGrade?: EvaluationGrade;
  }[];
}

// Final recommendation
export interface Recommendation {
  product: Product;
  rank: 1 | 2 | 3 | 4;
  finalScore: number;

  // PLP용: 한 줄 요약
  reasoning: string;

  // PDP용: 사용자 선택 태그 충족 여부
  selectedTagsEvaluation: Array<{
    userTag: string;
    tagType: 'pros' | 'cons';
    priority: number;
    status: '충족' | '부분충족' | '불충족' | '회피됨' | '부분회피' | '회피안됨';
    evidence: string;
    citations: number[];
    tradeoff?: string;
  }>;

  // PDP용: 추가 장점
  additionalPros: Array<{ text: string; citations: number[] }>;

  // PDP용: 단점
  cons: Array<{ text: string; citations: number[] }>;

  // PDP용: 비교 (리스트 형태)
  anchorComparison: Array<{ text: string; citations?: number[] }>;

  // PDP용: 구매 팁 (리스트 형태, 선택적)
  purchaseTip?: Array<{ text: string; citations?: number[] }>;

  // 리뷰 인용 데이터
  citedReviews: Array<{ index: number; text: string; rating: number }>;
}

// Conversational flow state
export interface ConversationalState {
  currentAttribute: keyof CoreValues | null;  // 현재 진행 중인 속성
  awaitingResponse: boolean;                   // 사용자 답변 대기 중
  hasAskedFollowUp: boolean;                   // 추가 질문 중인지 여부
  isIntroduced: boolean;                       // 인트로 완료 여부
}

// Favorite products state (for comparison feature)
export interface FavoritesState {
  productIds: string[];  // 찜한 제품 ID 목록 (최대 3개)
  timestamp: number;     // 마지막 업데이트 시간
}

// Session state
export interface SessionState {
  phase: 'home' | 'ranking' | 'priority' | 'chat1' | 'chat2' | 'result';
  messages: Message[];
  attributeAssessments: AttributeAssessment;
  currentAttribute: number;       // 현재 질문 중인 속성 (0-7)
  additionalContext: string[];    // Chat 2에서 수집한 추가 맥락
  phase0Context?: string;         // Phase 0 워밍업에서 수집한 자유 맥락
  accuracy: number;               // 추천 정확도 (80-100)
  conversationalState?: ConversationalState;  // 대화형 상태
  persona?: UserPersona;
  recommendations?: Recommendation[];
  contextSummary?: UserContextSummary;  // 사용자 맥락 요약

  // New flow fields
  prioritySettings?: PrioritySettings;  // Priority 페이지에서 설정한 값
  budget?: BudgetRange;                 // 예산 범위
  isQuickRecommendation?: boolean;      // 바로 추천받기 선택 여부
  chatConversations?: AttributeConversation[];  // 속성별 자유 대화 저장
  forceRegenerate?: boolean;            // 캐시 무시하고 새로 생성 (채팅 후 추천받기)

  // Step 3 (Product Preview) fields
  additionalInput?: string;             // Step 3에서 사용자가 입력한 추가 정보
  top10Products?: Product[];            // Step 3에서 필터링된 상위 10개 제품

  // Tag-based selection (New Priority flow)
  selectedProsTags?: string[];          // 선택된 장점 태그 IDs
  selectedConsTags?: string[];          // 선택된 단점 태그 IDs
  selectedAdditionalTags?: string[];    // 선택된 추가 고려사항 태그 IDs
  anchorProduct?: any;                  // Tag-based flow의 앵커 제품 (캐싱용)

  // Tracking fields
  phone?: string;                       // URL 파라미터로 전달된 전화번호 (?phone=01012345678)
  utmCampaign?: string;                 // UTM 캠페인 파라미터 (?utm_campaign=first)
}

// Gemini API request/response types
export interface GeminiMessage {
  role: 'user' | 'model';
  parts: { text: string }[];
}

export interface GeminiRequest {
  contents: GeminiMessage[];
  generationConfig?: {
    temperature?: number;
    topK?: number;
    topP?: number;
    maxOutputTokens?: number;
  };
}

export interface GeminiResponse {
  candidates: {
    content: {
      parts: { text: string }[];
      role: string;
    };
    finishReason: string;
  }[];
}
