// Auto-generated by scripts/extractCategoryAttributes.ts
// Generated at: 2025-12-02T05:53:54.382Z
// Do not edit manually

import { Category } from '@/lib/data';

export interface CategoryAttribute {
  key: string;
  name: string;
  description: string;
  importance: 'high' | 'medium' | 'low';
  examples: string[];
}

export const CATEGORY_ATTRIBUTES: Record<Category, CategoryAttribute[]> = {
  "baby_bottle": [
    {
      "key": "colic_prevention",
      "name": "배앓이 방지",
      "description": "수유 중 공기 유입을 차단하여 아기의 배앓이(가스, 복통)를 예방하는 기능성",
      "importance": "high",
      "examples": [
        "에어벤트 시스템",
        "공기 순환구",
        "트림 용이성",
        "진공 상태 방지",
        "가스 참 감소"
      ]
    },
    {
      "key": "cleaning_convenience",
      "name": "세척 편의성",
      "description": "젖병의 구조와 부품 수에 따른 세척 및 건조의 용이성",
      "importance": "high",
      "examples": [
        "넓은 입구(와이드넥)",
        "적은 부속품",
        "홈 없는 구조",
        "설거지 용이성",
        "전동솔 사용 가능"
      ]
    },
    {
      "key": "nipple_compatibility_acceptance",
      "name": "젖꼭지 호환 및 물림",
      "description": "타사 젖꼭지와의 호환성 여부 및 아기가 거부감 없이 잘 무는 정도",
      "importance": "high",
      "examples": [
        "더블하트/모윰 호환",
        "젖꼭지 거부 없음",
        "유두 혼동 없음",
        "편안한 흡입",
        "호환 링"
      ]
    },
    {
      "key": "leakage_assembly",
      "name": "누수 및 조립 편의성",
      "description": "젖병 결합 시의 난이도와 잘못된 결합으로 인한 내용물 샘 현상 여부",
      "importance": "high",
      "examples": [
        "결합 링 체결 난이도",
        "분유 샘 방지",
        "손목 무리 없음",
        "쉽게 열리는 뚜껑",
        "스크류 결합"
      ]
    },
    {
      "key": "material_safety",
      "name": "소재 및 안전성",
      "description": "젖병의 소재(PPSU, PP 등) 등급과 열탕/소독기 사용 가능 여부",
      "importance": "medium",
      "examples": [
        "PPSU 소재",
        "BPA FREE",
        "열탕 소독 가능",
        "UV 소독기 사용",
        "내열성"
      ]
    },
    {
      "key": "design_usability",
      "name": "디자인 및 사용 편의성",
      "description": "젖병의 형태, 그립감, 눈금 시인성, 뚜껑 모양 등 실사용 시의 디테일",
      "importance": "medium",
      "examples": [
        "굴러감 방지 뚜껑",
        "뒤집어 놓기 가능",
        "선명한 눈금",
        "그립감",
        "감성 디자인"
      ]
    },
    {
      "key": "device_compatibility",
      "name": "기기 호환성",
      "description": "유축기나 자동 분유 제조기 등 육아 가전과의 호환 여부",
      "importance": "medium",
      "examples": [
        "스펙트라 유축기 호환",
        "브라비/베이비브레짜 센서 인식",
        "유축 후 바로 수유",
        "보관 용이성"
      ]
    }
  ],
  "baby_bottle_sterilizer": [
    {
      "key": "sterilization_performance",
      "name": "살균 성능 및 방식",
      "description": "세균 제거 능력과 살균 광원(UV 램프 vs UV LED)의 종류 및 효율성",
      "importance": "high",
      "examples": [
        "UV-LED 적용 여부",
        "램프 교체 필요성",
        "사각지대 없는 살균",
        "바닥면 반사율",
        "살균 냄새 제거"
      ]
    },
    {
      "key": "drying_efficiency",
      "name": "건조 성능",
      "description": "젖병 내부와 부속품의 물기를 완전히 제거하는 능력 및 건조 시스템",
      "importance": "high",
      "examples": [
        "물기/물얼룩 잔여 여부",
        "건조 시간 조절(30/50/70분)",
        "저온 건조 방식",
        "건조 단독 모드 지원"
      ]
    },
    {
      "key": "capacity_and_storage",
      "name": "수납 용량 및 구조",
      "description": "한 번에 소독 가능한 젖병 개수와 내부 공간 활용성",
      "importance": "high",
      "examples": [
        "젖병 9~16개 동시 수납",
        "선반 높이 조절/탈부착",
        "긴 젖병 수납 가능 여부",
        "상단/하단 바구니 구조"
      ]
    },
    {
      "key": "sterile_storage_mode",
      "name": "보관 기능 (스토리지)",
      "description": "살균 건조 후 무균 상태로 유지해주는 보관 기능의 유무 및 성능",
      "importance": "high",
      "examples": [
        "자동 보관 모드(멸균 유지)",
        "주기적 자동 살균/환기",
        "최대 보관 시간",
        "문을 열어도 리셋되지 않는 보관"
      ]
    },
    {
      "key": "maintenance_and_hygiene",
      "name": "관리 및 위생",
      "description": "기기 내부 청소의 용이성과 위생적인 소재 사용 여부",
      "importance": "medium",
      "examples": [
        "물받침대 유무 및 세척",
        "내부 슈퍼미러 스테인리스 소재",
        "필터 교체 및 청소",
        "바닥 물때 관리"
      ]
    },
    {
      "key": "design_and_size",
      "name": "디자인 및 크기",
      "description": "주방 인테리어와의 조화 및 설치 공간 차지 비중",
      "importance": "medium",
      "examples": [
        "주방 인테리어 조화(맘마존)",
        "제품 부피 및 설치 공간",
        "도어 개폐 방향(좌/우)",
        "색상 및 마감 재질"
      ]
    },
    {
      "key": "usability_and_noise",
      "name": "사용 편의성 및 소음",
      "description": "조작의 직관성과 작동 시 발생하는 소음 수준",
      "importance": "medium",
      "examples": [
        "작동 소음(팬 소리)",
        "남은 시간/온도 디스플레이",
        "도어 오픈 감지 센서",
        "원터치 자동 코스"
      ]
    }
  ],
  "baby_formula_dispenser": [
    {
      "key": "mixing_accuracy",
      "name": "조유 정확도 및 혼합력",
      "description": "설정된 농도대로 정확하게 조유되는지와 뭉침이나 거품 없이 잘 섞이는지 여부",
      "importance": "high",
      "examples": [
        "농도 정확성",
        "분유 뭉침 없음",
        "거품 발생 적음",
        "물과 분유 비율",
        "잘 녹지 않는 분유 호환"
      ]
    },
    {
      "key": "hygiene_maintenance",
      "name": "위생 및 세척 편의성",
      "description": "부품 분해/조립의 용이성, 세척 주기 및 알림, 내부 세척 난이도",
      "importance": "high",
      "examples": [
        "깔때기 세척 알림(4회)",
        "부품 분해 세척",
        "물통 세척 용이성",
        "노즐 청소",
        "식초 세척/내부 건조"
      ]
    },
    {
      "key": "volume_control",
      "name": "출수량 조절 단위",
      "description": "분유 제조량을 얼마나 세밀하게 조절할 수 있는지 (분유 낭비 방지 및 신생아 수유량 맞춤)",
      "importance": "high",
      "examples": [
        "10ml 단위 조절",
        "30ml 단위 조절",
        "최소 조유량(60ml 등)",
        "분유 낭비 최소화",
        "정량 출수"
      ]
    },
    {
      "key": "speed_convenience",
      "name": "조유 속도 및 편의성",
      "description": "버튼 조작 후 분유가 완성되기까지 걸리는 시간과 조작의 직관성 (특히 새벽 수유 시 중요)",
      "importance": "high",
      "examples": [
        "7초 완성",
        "원터치 작동",
        "밤중/새벽 수유 편리함",
        "직관적인 버튼",
        "스마트폰 연동"
      ]
    },
    {
      "key": "temperature_control",
      "name": "온도 조절",
      "description": "원하는 온도로 설정 가능 여부 및 온도의 정확성과 유지 능력",
      "importance": "medium",
      "examples": [
        "1도 단위 조절",
        "3단계 온도 설정",
        "순간 가열 방식",
        "보온 유지",
        "물만 출수 기능"
      ]
    },
    {
      "key": "formula_compatibility",
      "name": "분유 호환성 및 세팅",
      "description": "다양한 브랜드의 분유를 지원하는지, 세팅값 찾기 및 설정의 용이성",
      "importance": "medium",
      "examples": [
        "분유 세팅 번호",
        "바코드 스캔 설정",
        "해외/국내 분유 호환",
        "특수 분유 지원",
        "공식 홈페이지 가이드"
      ]
    },
    {
      "key": "noise_level",
      "name": "소음",
      "description": "작동 시 발생하는 모터 및 기계음의 크기 (아기 수면 방해 여부)",
      "importance": "medium",
      "examples": [
        "커피머신 정도 소음",
        "새벽 사용 시 소음",
        "진동 소리",
        "조용한 작동",
        "기계음 크기"
      ]
    },
    {
      "key": "durability_safety",
      "name": "내구성 및 안전성",
      "description": "제품의 마감 상태, 센서 오류 빈도, 소재의 안전성",
      "importance": "medium",
      "examples": [
        "센서 오류(물 부족/깔때기)",
        "부품 갈림(플라스틱 이슈)",
        "물통 결합 내구성",
        "전선 접촉 불량",
        "소재 안전성"
      ]
    }
  ],
  "baby_monitor": [
    {
      "key": "image_quality_and_night_vision",
      "name": "화질 및 야간 모드",
      "description": "주간 및 야간(저조도) 환경에서의 영상 선명도와 해상도, 식별 능력",
      "importance": "high",
      "examples": [
        "2K QHD 해상도",
        "적외선 나이트 비전",
        "디지털 줌 선명도",
        "얼굴/표정 식별 가능"
      ]
    },
    {
      "key": "security_privacy",
      "name": "보안 및 프라이버시",
      "description": "해킹 방지를 위한 보안 기술 및 사생활 보호를 위한 물리적/소프트웨어적 기능",
      "importance": "high",
      "examples": [
        "AES-256 암호화",
        "물리적 렌즈 차단(프라이버시 모드)",
        "서버 위치(AWS 등)",
        "해킹 방지"
      ]
    },
    {
      "key": "detection_alerts",
      "name": "감지 및 알림 정확도",
      "description": "움직임이나 소리를 감지하여 사용자에게 알리는 기능의 정확성과 속도",
      "importance": "high",
      "examples": [
        "아기 울음 감지",
        "모션 감지 민감도",
        "AI 피사체 추적",
        "실시간 푸시 알림"
      ]
    },
    {
      "key": "connectivity_app_usability",
      "name": "연결성 및 앱 편의성",
      "description": "Wi-Fi 연결의 안정성, 앱 인터페이스의 직관성, 반응 속도(지연 시간)",
      "importance": "high",
      "examples": [
        "2.4GHz/5GHz 지원 여부",
        "앱 UI 직관성",
        "영상 지연(레이턴시)",
        "다중 기기 접속"
      ]
    },
    {
      "key": "fov_rotation",
      "name": "화각 및 회전 기능",
      "description": "카메라가 커버할 수 있는 시야 범위와 원격 회전(Pan/Tilt) 제어 능력",
      "importance": "medium",
      "examples": [
        "360도 회전",
        "상하 틸트",
        "사각지대 없음",
        "광각 렌즈"
      ]
    },
    {
      "key": "two_way_audio",
      "name": "양방향 오디오",
      "description": "앱과 카메라 간의 실시간 음성 소통 품질 및 마이크/스피커 성능",
      "importance": "medium",
      "examples": [
        "양방향 통화",
        "마이크 감도",
        "스피커 음질",
        "소리 전달 딜레이"
      ]
    },
    {
      "key": "storage_subscription",
      "name": "저장 방식 및 구독 비용",
      "description": "영상 저장 매체 지원 여부와 클라우드 서비스 등의 추가 유지 비용",
      "importance": "medium",
      "examples": [
        "MicroSD 카드 지원",
        "클라우드 유료 구독",
        "상시 녹화 기능",
        "추가 비용 없음"
      ]
    }
  ],
  "baby_play_mat": [
    {
      "key": "safety_and_cushioning",
      "name": "안전성 및 쿠션감",
      "description": "충격 흡수 능력과 아이 보호 기능 (두께, 탄성, 넘어짐 보호)",
      "importance": "high",
      "examples": [
        "4cm 두께",
        "머리 쿵 보호",
        "충격 흡수",
        "탄탄한 쿠션",
        "배밀이/걸음마 보호"
      ]
    },
    {
      "key": "noise_reduction",
      "name": "층간소음 방지",
      "description": "발망치 소리 및 생활 소음 차단 능력 (방음 효과, 진동 흡수)",
      "importance": "high",
      "examples": [
        "아랫집 민원 해결",
        "뛰는 소리 차단",
        "장난감 던지는 소리 흡수",
        "발소리 감소",
        "진동 저감"
      ]
    },
    {
      "key": "cleaning_and_maintenance",
      "name": "청소 및 관리 편의성",
      "description": "오염 제거 용이성 및 먼지 관리 (방수, 틈새 청소, 이염 관리)",
      "importance": "high",
      "examples": [
        "생활 방수",
        "틈새 먼지 끼임",
        "물티슈 청소",
        "이염 제거",
        "커버 분리 세탁"
      ]
    },
    {
      "key": "durability_and_resilience",
      "name": "내구성 및 복원력",
      "description": "장기간 사용 시 형태 유지 및 눌림 회복 능력 (꺼짐 현상, 스크래치 저항)",
      "importance": "medium",
      "examples": [
        "눌림 복원력",
        "가죽 늘어짐 방지",
        "코팅 벗겨짐",
        "장기간 사용 시 꺼짐",
        "스크래치 내구성"
      ]
    },
    {
      "key": "usability_and_convenience",
      "name": "사용 편의성",
      "description": "보관, 이동 및 가전제품과의 호환성 (접이식 구조, 로봇청소기 사용 가능 여부)",
      "importance": "medium",
      "examples": [
        "폴더형 접이식 보관",
        "로봇청소기 등반 불가",
        "가벼운 이동",
        "공간 확장성",
        "양면 활용"
      ]
    },
    {
      "key": "material_quality",
      "name": "소재 및 촉감",
      "description": "피부에 닿는 느낌과 소재의 안전성 (냄새, 소리, 미끄러짐)",
      "importance": "medium",
      "examples": [
        "초기 냄새",
        "뽀드득 소리",
        "부드러운 촉감",
        "피부 자극 없음",
        "미끄럼 방지 코팅"
      ]
    },
    {
      "key": "installation_and_fixation",
      "name": "설치 및 고정력",
      "description": "바닥 밀림 방지 및 공간 맞춤 설치 용이성 (밀림 현상, 재단 가능 여부)",
      "importance": "medium",
      "examples": [
        "바닥 밀림 현상",
        "실리콘 테이프 고정",
        "셀프 재단(DIY)",
        "빈틈없는 시공",
        "사이즈 맞춤"
      ]
    },
    {
      "key": "design_and_aesthetics",
      "name": "디자인 및 심미성",
      "description": "인테리어와의 조화 및 색상 (색감, 패턴, 분위기)",
      "importance": "medium",
      "examples": [
        "인테리어 조화",
        "크림/그레이 색상",
        "양면 디자인",
        "마블 패턴",
        "깔끔한 마감"
      ]
    }
  ],
  "nasal_aspirator": [
    {
      "key": "suction_power",
      "name": "흡입력",
      "description": "콧물을 얼마나 효과적으로 제거할 수 있는지에 대한 성능 (묽은 콧물 vs 끈적한 콧물, 깊은 콧물 제거 능력)",
      "importance": "high",
      "examples": [
        "끈적한 콧물 제거",
        "깊은 콧물 흡입",
        "흡입 강도 조절",
        "병원용 석션 비교"
      ]
    },
    {
      "key": "cleaning_hygiene",
      "name": "세척 및 위생",
      "description": "부품 분리 및 세척의 용이성과 위생적인 관리 가능 여부 (역류 방지 구조 포함)",
      "importance": "high",
      "examples": [
        "완전 분리 세척",
        "열탕 소독 가능",
        "역류 방지 구조",
        "세척솔 포함 여부"
      ]
    },
    {
      "key": "noise_vibration",
      "name": "소음 및 진동",
      "description": "작동 시 발생하는 소음과 진동의 크기 (아이가 놀라거나 거부감을 느끼는지 여부)",
      "importance": "high",
      "examples": [
        "저소음 모터",
        "진동 세기",
        "아기 거부감",
        "멜로디 기능"
      ]
    },
    {
      "key": "tip_design_comfort",
      "name": "팁 디자인 및 자극",
      "description": "콧구멍에 닿는 팁의 재질, 크기, 모양 및 점막 자극 여부",
      "importance": "medium",
      "examples": [
        "부드러운 실리콘 팁",
        "팁 사이즈(대/소)",
        "점막 상처 방지",
        "밀착력"
      ]
    },
    {
      "key": "portability_power",
      "name": "휴대성 및 전원",
      "description": "제품의 크기, 무게 및 전원 방식(건전지/충전식/유선)에 따른 이동 편의성",
      "importance": "medium",
      "examples": [
        "컴팩트한 사이즈",
        "건전지 교체형",
        "무선 사용",
        "여행/외출 시 휴대"
      ]
    },
    {
      "key": "durability_build_quality",
      "name": "내구성 및 마감",
      "description": "제품의 튼튼함, 방수 성능 및 고장 발생 빈도 (특히 본체 내부로 액체 유입 시)",
      "importance": "medium",
      "examples": [
        "생활 방수",
        "모터 수명",
        "배터리 접촉 불량",
        "부품 결합 상태"
      ]
    },
    {
      "key": "ease_of_use",
      "name": "사용 편의성",
      "description": "조작의 간편함과 부가 기능의 유용성",
      "importance": "medium",
      "examples": [
        "원터치 버튼",
        "그립감",
        "투명 저장통(콧물 확인)",
        "멜로디 재생"
      ]
    }
  ],
  "thermometer": [
    {
      "key": "accuracy_consistency",
      "name": "정확도 및 일관성",
      "description": "실제 체온과의 일치 여부 및 반복 측정 시 수치의 변화 폭 (병원 측정값과의 비교, 오차 범위)",
      "importance": "high",
      "examples": [
        "병원 측정값과 일치",
        "반복 측정 시 오차 없음",
        "들쭉날쭉한 수치",
        "정밀한 센서 감지",
        "예열 팁 기술"
      ]
    },
    {
      "key": "measurement_speed",
      "name": "측정 속도",
      "description": "체온 측정 완료까지 걸리는 시간 (아이의 거부감을 줄이기 위한 신속성)",
      "importance": "high",
      "examples": [
        "1초 측정",
        "누르자마자 확인",
        "빠른 반응 속도",
        "움직이는 아이 측정 용이",
        "대기 시간 없음"
      ]
    },
    {
      "key": "display_night_usability",
      "name": "디스플레이 및 야간 사용성",
      "description": "어두운 환경에서의 화면 식별 용이성 및 화면 구성 (백라이트 유무, 글자 크기)",
      "importance": "high",
      "examples": [
        "백라이트 기능",
        "야간 조명",
        "큰 LCD 숫자",
        "어두운 방에서 확인 가능",
        "발열 시 화면 색상 변화"
      ]
    },
    {
      "key": "hygiene_maintenance",
      "name": "위생 및 필터 관리",
      "description": "교차 감염 방지를 위한 위생 관리 방식 및 소모품 유지 보수 (렌즈 필터 사용 여부 및 교체 편의성)",
      "importance": "high",
      "examples": [
        "일회용 렌즈 필터",
        "교차 감염 방지",
        "필터 교체 비용",
        "필터 탈부착 버튼",
        "캡 포함 여부"
      ]
    },
    {
      "key": "ease_of_use",
      "name": "사용 편의성 및 조작감",
      "description": "제품의 그립감, 버튼 구성, 휴대성 등 물리적인 사용 용이성",
      "importance": "medium",
      "examples": [
        "한 손 조작",
        "간편한 버튼 구성",
        "그립감",
        "가벼운 무게",
        "직관적인 인터페이스"
      ]
    },
    {
      "key": "sound_memory_features",
      "name": "소리 및 메모리 기능",
      "description": "측정 알림음 제어 및 이전 기록 저장 기능 (무음 모드, 기록 저장 개수)",
      "importance": "medium",
      "examples": [
        "무음/음소거 기능",
        "측정 완료 비프음",
        "최근 기록 저장(메모리)",
        "연령별 설정 기능",
        "에러 알림음"
      ]
    },
    {
      "key": "durability_as",
      "name": "내구성 및 AS",
      "description": "제품의 수명, 충격 저항성 및 사후 지원 서비스",
      "importance": "medium",
      "examples": [
        "낙하 시 파손 여부",
        "잔고장 없음",
        "10년 사용",
        "보상 판매 서비스",
        "배터리 수명"
      ]
    }
  ],
  "car_seat": [
    {
      "key": "safety_stability",
      "name": "안전성 및 고정력",
      "description": "차량 장착 시 흔들림 없는 고정력과 충격 보호 기능 (인증 여부, 측면 보호 포함)",
      "importance": "high",
      "examples": [
        "ISOFIX 고정",
        "I-SIZE 인증",
        "측면 충격 보호(SPS)",
        "서포트 레그",
        "주행 중 흔들림 없음"
      ]
    },
    {
      "key": "comfort_recline",
      "name": "착석감 및 각도 조절",
      "description": "아이가 장시간 탑승 시 느끼는 편안함과 수면 시 목 꺾임 방지를 위한 등받이 각도",
      "importance": "high",
      "examples": [
        "등받이 리클라이닝",
        "목 꺾임 방지",
        "메모리폼 쿠션",
        "발받침 유무",
        "넓은 좌석 공간"
      ]
    },
    {
      "key": "boarding_convenience",
      "name": "승하차 편의성",
      "description": "아이를 태우고 내릴 때 부모의 편리함 (회전 기능 및 벨트 체결 용이성)",
      "importance": "high",
      "examples": [
        "360도 회전",
        "마그네틱 안전벨트 홀더",
        "안전벨트 가이드",
        "원터치 회전 버튼",
        "아이 스스로 벨트 착용"
      ]
    },
    {
      "key": "installation_portability",
      "name": "설치 및 휴대성",
      "description": "차량 간 이동 설치의 용이성과 제품의 무게 및 부피",
      "importance": "medium",
      "examples": [
        "가벼운 무게",
        "간편한 ISOFIX 체결",
        "폴딩 기능",
        "기내 반입 가능",
        "세컨카 이동 설치"
      ]
    },
    {
      "key": "fabric_hygiene",
      "name": "소재 및 세탁 편의성",
      "description": "통기성 좋은 소재 사용 여부와 오염 시 커버 분리 및 세탁의 용이성",
      "importance": "medium",
      "examples": [
        "에어매쉬 소재",
        "커버 분리 세탁",
        "부드러운 촉감",
        "땀 배출 통기성",
        "오염에 강한 색상"
      ]
    },
    {
      "key": "adjustability_growth",
      "name": "성장 맞춤 조절",
      "description": "아이의 성장에 따라 헤드레스트 높이 및 시트 폭을 조절할 수 있는 기능",
      "importance": "medium",
      "examples": [
        "헤드레스트 높이 조절",
        "어깨 폭 확장",
        "이너시트 단계별 제거",
        "주니어 모드 변환",
        "긴 사용 기간"
      ]
    }
  ],
  "milk_powder_port": [
    {
      "key": "temperature_control_preservation",
      "name": "온도 조절 및 보온 유지",
      "description": "설정한 온도로 정확하게 맞추고 장시간(24시간 이상) 일정하게 유지하는 능력",
      "importance": "high",
      "examples": [
        "1도 단위 미세 조절",
        "영구 보온(24시간 유지)",
        "40~45도 분유 모드",
        "설정 온도 기억(메모리 기능)"
      ]
    },
    {
      "key": "cooling_speed",
      "name": "쿨링 속도 (식힘 기능)",
      "description": "100도로 끓인 물을 분유 타기 적절한 온도(40~45도)로 빠르게 식혀주는 성능",
      "importance": "high",
      "examples": [
        "쿨링팬 탑재",
        "빠른 식힘(1~2시간 내)",
        "급속 냉각 시스템",
        "자연 냉각 대비 시간 단축"
      ]
    },
    {
      "key": "material_safety",
      "name": "소재 안전성",
      "description": "아기에게 유해한 물질이 나오지 않는 안전한 소재 사용 여부 및 마감 처리",
      "importance": "high",
      "examples": [
        "SUS316 (의료용 스테인리스)",
        "붕규산 내열 강화유리",
        "접착제(실리콘) 미사용",
        "연마제 제거 용이성"
      ]
    },
    {
      "key": "hygiene_maintenance",
      "name": "세척 및 위생 관리",
      "description": "물통 내부와 뚜껑 등을 위생적으로 관리하고 세척하기 쉬운 구조인지 여부",
      "importance": "high",
      "examples": [
        "통세척 가능",
        "뚜껑 완전 분리",
        "넓은 입구",
        "이음새 없는 바닥 구조"
      ]
    },
    {
      "key": "chlorine_removal",
      "name": "염소 제거 및 살균",
      "description": "수돗물의 잔류 염소를 제거하기 위해 100도에서 일정 시간 이상 가열하는 기능",
      "importance": "medium",
      "examples": [
        "3~5분 안심 살균",
        "염소 제거 모드",
        "100도 가열 후 자동 식힘",
        "배앓이 방지 기능"
      ]
    },
    {
      "key": "night_usability",
      "name": "야간 사용 편의성",
      "description": "새벽 수유 시 아기나 가족을 깨우지 않고 조작할 수 있는 기능",
      "importance": "medium",
      "examples": [
        "음소거(무음) 모드",
        "LED 디스플레이 시인성",
        "터치 조작음 제거",
        "수유등 기능"
      ]
    },
    {
      "key": "capacity_ergonomics",
      "name": "용량 및 무게 (손목 부담)",
      "description": "하루 수유량을 감당할 수 있는 용량과 산모의 손목에 무리가 가지 않는 무게",
      "importance": "medium",
      "examples": [
        "1.3L 대용량",
        "유리 무게로 인한 손목 부담",
        "안정적인 손잡이 그립감",
        "하루 1~2회 물 보충"
      ]
    },
    {
      "key": "versatility",
      "name": "다용도 활용성",
      "description": "분유 수유 시기 이후에도 티포트, 요거트 메이커 등으로 활용 가능한지 여부",
      "importance": "low",
      "examples": [
        "티마스터(차망 포함)",
        "중탕 기능",
        "요거트 제조 모드",
        "이유식 데우기"
      ]
    }
  ]
} as const;
