// Auto-generated by scripts/extractCategoryAttributes.ts
// Generated at: 2025-11-28T06:04:17.094Z
// Do not edit manually

import { Category } from '@/lib/data';

export interface CategoryAttribute {
  key: string;
  name: string;
  description: string;
  importance: 'high' | 'medium' | 'low';
  examples: string[];
}

export const CATEGORY_ATTRIBUTES: Record<Category, CategoryAttribute[]> = {
  "baby_bottle": [
    {
      "key": "colic_prevention",
      "name": "배앓이 방지",
      "description": "수유 중 공기 유입을 차단하여 배앓이, 용트림, 가스 참 등을 예방하는 기능성",
      "importance": "high",
      "examples": [
        "에어벤트 시스템",
        "공기 순환 링",
        "진공 상태 방지",
        "트림 용이성",
        "용트림 감소"
      ]
    },
    {
      "key": "cleaning_convenience",
      "name": "세척 편의성",
      "description": "젖병 입구의 크기, 부속품의 개수, 틈새 유무 등에 따른 세척 및 관리의 용이성",
      "importance": "high",
      "examples": [
        "넓은 입구(와이드넥)",
        "세척 솔 진입 용이",
        "입구 홈/틈새 세척 어려움",
        "부속품 개수",
        "식기세척기 사용"
      ]
    },
    {
      "key": "nipple_acceptance_compatibility",
      "name": "젖꼭지 거부 및 호환성",
      "description": "아기가 거부감 없이 무는지 여부와 타사 인기 젖꼭지(더블하트 등)와의 호환 가능성",
      "importance": "high",
      "examples": [
        "더블하트 젖꼭지 호환",
        "유두 혼동 없음",
        "부드러운 실리콘",
        "적절한 유속",
        "물기 편한 모양"
      ]
    },
    {
      "key": "leakage_assembly",
      "name": "샘 현상 및 조립 편의성",
      "description": "부속품 결합의 난이도와 잘못 결합했을 때 분유가 새는 현상의 발생 빈도",
      "importance": "high",
      "examples": [
        "결합 시 누수",
        "링 체결 번거로움",
        "고무링 끼우기",
        "흔들 때 샜음",
        "조립 난이도"
      ]
    },
    {
      "key": "material_safety",
      "name": "소재 및 안전성",
      "description": "젖병의 소재(PPSU, 유리, PP 등)에 따른 안전성, 내열성, 그리고 무게(손목 부담)",
      "importance": "medium",
      "examples": [
        "PPSU 소재",
        "유리 젖병 무게",
        "열탕 소독 가능",
        "BPA FREE",
        "가벼운 무게"
      ]
    },
    {
      "key": "design_usability",
      "name": "디자인 및 사용 편의성",
      "description": "그립감, 뚜껑의 형태, 눈금 시인성 등 실사용 시 느껴지는 편의 요소",
      "importance": "medium",
      "examples": [
        "굴러가는 둥근 뚜껑",
        "뒤집어 놓을 수 없는 뚜껑",
        "잡기 편한 그립감",
        "선명한 눈금",
        "보관 용이성"
      ]
    },
    {
      "key": "device_compatibility",
      "name": "기기 호환성",
      "description": "유축기, 자동 분유 제조기 등 육아 보조 기기와의 연동성",
      "importance": "medium",
      "examples": [
        "스펙트라 유축기 호환",
        "브라비/브레짜 센서 인식",
        "유축 후 바로 수유",
        "소독기 수납 높이"
      ]
    }
  ],
  "baby_bottle_sterilizer": [
    {
      "key": "sterilization_drying_performance",
      "name": "살균 및 건조 성능",
      "description": "세균 제거 능력과 물기 없는 완벽한 건조 여부, 램프 방식(UV 램프 vs UV LED)에 따른 효율성",
      "importance": "high",
      "examples": [
        "UV-C LED",
        "물기 없는 건조",
        "램프 교체 필요성",
        "살균 냄새 제거",
        "99.9% 살균력"
      ]
    },
    {
      "key": "capacity_storage",
      "name": "수납 용량 및 보관성",
      "description": "내부 공간의 크기, 선반 활용도, 그리고 살균 후 멸균 상태로 보관하는 기능의 유무",
      "importance": "high",
      "examples": [
        "젖병 9개 이상 수납",
        "탈부착 선반",
        "높은 젖병 수납",
        "멸균 보관 모드",
        "장난감/식판 수납"
      ]
    },
    {
      "key": "durability_build_quality",
      "name": "내구성 및 마감 품질",
      "description": "제품의 수명, 문 경첩 및 버튼의 견고함, 초기 불량률 및 AS 용이성",
      "importance": "high",
      "examples": [
        "문 처짐/유격",
        "터치 패널 고장",
        "팬 모터 수명",
        "배송 중 파손",
        "AS 응대 및 비용"
      ]
    },
    {
      "key": "usability_interface",
      "name": "사용 편의성 및 조작",
      "description": "작동 방식의 직관성, 디스플레이 시인성, 자동화 기능 등 사용자의 조작 편의",
      "importance": "high",
      "examples": [
        "원터치 오토 모드",
        "남은 시간 표시",
        "도어 오픈 감지 센서",
        "내부 조명",
        "직관적 버튼"
      ]
    },
    {
      "key": "noise_level",
      "name": "소음 수준",
      "description": "건조 및 환기 팬 작동 시 발생하는 소음의 크기와 거슬림 정도",
      "importance": "medium",
      "examples": [
        "팬 작동 소음",
        "고주파음(윙 소리)",
        "무음 모드",
        "종료 알림음",
        "수면 방해 여부"
      ]
    },
    {
      "key": "maintenance_hygiene",
      "name": "관리 및 위생",
      "description": "내부 청소의 용이성, 물때 관리, 소재의 안전성",
      "importance": "medium",
      "examples": [
        "스테인리스 내부",
        "물받이 트레이",
        "바닥 물때 청소",
        "램프 교체 주기",
        "청소 알림 기능"
      ]
    },
    {
      "key": "design_aesthetics",
      "name": "디자인 및 심미성",
      "description": "제품의 외관, 색상, 주방 인테리어와의 조화",
      "importance": "medium",
      "examples": [
        "감성적인 색상",
        "매트한 질감",
        "미니멀 디자인",
        "공간 차지 면적",
        "인테리어 조화"
      ]
    },
    {
      "key": "portability",
      "name": "휴대성 (휴대용 제품 한정)",
      "description": "외출 및 여행 시 가지고 다닐 수 있는 무게, 크기, 배터리 효율",
      "importance": "low",
      "examples": [
        "가벼운 무게",
        "충전식 배터리",
        "컴팩트한 사이즈",
        "쪽쪽이 전용",
        "여행용 파우치"
      ]
    }
  ],
  "baby_formula_dispenser": [
    {
      "key": "mixing_accuracy_and_consistency",
      "name": "조유 정확도 및 혼합력",
      "description": "설정된 농도대로 정확하게 물과 분유가 배합되는지와 뭉침이나 거품 없이 잘 섞이는지 여부",
      "importance": "high",
      "examples": [
        "농도 정확성",
        "분유 뭉침 없음",
        "거품 발생 최소화",
        "물/분유 비율 일관성"
      ]
    },
    {
      "key": "cleaning_and_maintenance",
      "name": "세척 및 관리 편의성",
      "description": "부품 분해/조립의 용이성, 세척 빈도 및 알림 기능, 위생 관리의 난이도",
      "importance": "high",
      "examples": [
        "깔때기 세척 주기(4회)",
        "물통 분리 난이도",
        "부품 완전 분해",
        "세척 알림 기능"
      ]
    },
    {
      "key": "volume_control_increments",
      "name": "출수량 조절 단위",
      "description": "분유 낭비를 줄이기 위해 얼마나 세밀하게 조유량을 설정할 수 있는지 여부",
      "importance": "high",
      "examples": [
        "10ml 단위 조절",
        "30ml 단위 조절",
        "최소 조유량(60ml 등)",
        "잔여 분유 낭비 방지"
      ]
    },
    {
      "key": "speed_and_ease_of_use",
      "name": "조유 속도 및 사용 편의성",
      "description": "버튼 조작의 직관성과 분유가 제조되어 나오는 속도 (특히 새벽 수유 시 중요)",
      "importance": "high",
      "examples": [
        "7초 조유",
        "원터치 작동",
        "직관적인 인터페이스",
        "앱 연동 기능"
      ]
    },
    {
      "key": "temperature_control",
      "name": "온도 조절 능력",
      "description": "아기가 바로 먹을 수 있는 온도로 정확하게 맞추고 유지하는 기능",
      "importance": "medium",
      "examples": [
        "1도 단위 미세 조절",
        "3단계 온도 설정",
        "순간 가열 방식",
        "보온 유지 기능"
      ]
    },
    {
      "key": "formula_compatibility",
      "name": "분유 호환성 및 세팅",
      "description": "다양한 브랜드의 분유(특수분유 포함)에 대한 세팅값 지원 및 변경 용이성",
      "importance": "medium",
      "examples": [
        "제조사별 세팅 번호",
        "특수 분유 호환",
        "잘 녹지 않는 분유 대응",
        "세팅값 변경 편의성"
      ]
    },
    {
      "key": "noise_level",
      "name": "소음 수준",
      "description": "작동 시 발생하는 모터 소음 및 진동의 크기 (밤중 수유 시 아기 수면 방해 여부)",
      "importance": "medium",
      "examples": [
        "모터 소음",
        "진동 소리",
        "조용한 밤 수유",
        "알림음 크기"
      ]
    },
    {
      "key": "durability_and_build_quality",
      "name": "내구성 및 마감 품질",
      "description": "제품 소재의 안전성, 부품의 견고함, 장기간 사용 시 고장 여부",
      "importance": "medium",
      "examples": [
        "플라스틱 갈림 이슈",
        "물통 결합부 내구성",
        "센서 오류 빈도",
        "마감 처리"
      ]
    }
  ],
  "baby_monitor": [
    {
      "key": "image_quality_night_vision",
      "name": "화질 및 야간 모드",
      "description": "주간 및 야간 환경에서의 영상 선명도, 해상도, 식별 능력 (얼굴, 작은 움직임 등)",
      "importance": "high",
      "examples": [
        "2K QHD/300만 화소 해상도",
        "적외선 나이트 비전",
        "디지털 줌 선명도",
        "야간 식별 거리(9m 등)",
        "빛 번짐 없는 선명함"
      ]
    },
    {
      "key": "smart_detection_tracking",
      "name": "스마트 감지 및 추적",
      "description": "움직임이나 소리를 감지하고 대상을 자동으로 따라가는 AI 기능의 정확도와 반응 속도",
      "importance": "high",
      "examples": [
        "모션 감지 및 알림",
        "AI 피사체(사람/반려동물) 추적",
        "아기 울음 소리 감지",
        "활동 구역 설정",
        "반응 속도(지연 시간)"
      ]
    },
    {
      "key": "security_privacy",
      "name": "보안 및 프라이버시",
      "description": "해킹 방지 기술 및 사생활 보호를 위한 물리적/소프트웨어적 기능",
      "importance": "high",
      "examples": [
        "프라이버시 모드(렌즈 물리적 차단)",
        "AES-256 암호화",
        "화이트 리스트 보안 방식",
        "서버 위치 및 신뢰성",
        "계정 이중 보안"
      ]
    },
    {
      "key": "connectivity_app_usability",
      "name": "연결성 및 앱 편의성",
      "description": "Wi-Fi 연결 안정성, 초기 설치 난이도, 전용 앱의 UI/UX 및 기능 편의성",
      "importance": "high",
      "examples": [
        "QR코드 간편 설치",
        "Wi-Fi 연결 안정성(2.4GHz/5GHz)",
        "앱 내 다중 기기 모니터링",
        "가족 공유 기능",
        "실시간 스트리밍 지연 최소화"
      ]
    },
    {
      "key": "field_of_view_rotation",
      "name": "화각 및 회전 기능",
      "description": "카메라가 커버할 수 있는 시야 범위와 원격 회전 제어 능력",
      "importance": "medium",
      "examples": [
        "360도 수평 회전",
        "114도 수직 틸트",
        "사각지대 없는 커버력",
        "원격 각도 조절",
        "광각 렌즈"
      ]
    },
    {
      "key": "storage_recording",
      "name": "저장 방식 및 녹화",
      "description": "영상 데이터 저장 매체 지원 여부 및 녹화 방식의 유연성",
      "importance": "medium",
      "examples": [
        "MicroSD 카드 지원(최대 용량)",
        "클라우드 저장 서비스(유/무료)",
        "이벤트 녹화 vs 상시 녹화",
        "자동 루프 레코딩",
        "NAS/RTSP 지원"
      ]
    },
    {
      "key": "two_way_audio",
      "name": "양방향 오디오",
      "description": "앱과 카메라 간의 실시간 음성 소통 품질 및 마이크 감도",
      "importance": "medium",
      "examples": [
        "양방향 음성 통화",
        "고감도 마이크",
        "반려동물/아기에게 말하기",
        "외부 소음 청취",
        "경고 방송 송출"
      ]
    }
  ],
  "baby_play_mat": [
    {
      "key": "cushioning_safety",
      "name": "쿠션감 및 안전성",
      "description": "아이의 낙상 사고 방지와 충격 흡수 능력, 매트의 두께 및 탄탄함 정도",
      "importance": "high",
      "examples": [
        "4cm 두께",
        "머리 쿵 보호",
        "탄탄한 고밀도 폼",
        "충격 흡수력",
        "배밀이/걸음마 보호"
      ]
    },
    {
      "key": "noise_reduction",
      "name": "층간소음 방지",
      "description": "아이들이 뛰거나 물건을 던질 때 발생하는 소음을 차단하여 이웃 간 분쟁을 예방하는 능력",
      "importance": "high",
      "examples": [
        "발망치 소리 차단",
        "장난감 던지는 소리 흡수",
        "아랫집 민원 해결",
        "뛰어놀기 가능",
        "진동 흡수"
      ]
    },
    {
      "key": "cleaning_hygiene",
      "name": "청소 및 위생 관리",
      "description": "오염 물질 제거의 용이성, 방수 기능, 틈새 먼지 끼임 관리 편의성",
      "importance": "high",
      "examples": [
        "생활 방수",
        "물티슈로 닦임",
        "접이식 틈새 먼지 끼임",
        "이물질/음료수 처리",
        "볼펜/낙서 지워짐"
      ]
    },
    {
      "key": "durability_resilience",
      "name": "내구성 및 복원력",
      "description": "장기간 사용 시 꺼짐 현상 여부, 무거운 가구에 눌린 자국 복원 속도, 표면 스크래치 저항성",
      "importance": "medium",
      "examples": [
        "폼 꺼짐 현상",
        "눌림 자국 복원",
        "가죽 늘어짐",
        "반려동물 발톱 스크래치",
        "장기간 사용 시 변형"
      ]
    },
    {
      "key": "usability_compatibility",
      "name": "사용 편의성 및 호환성",
      "description": "매트의 고정력(밀림 방지), 보관/이동의 용이성, 로봇청소기 사용 가능 여부",
      "importance": "medium",
      "examples": [
        "로봇청소기 등반 불가",
        "바닥 밀림 현상",
        "폴더형 접어서 보관",
        "가벼운 무게",
        "실리콘 테이프 고정 필요"
      ]
    },
    {
      "key": "design_aesthetics",
      "name": "디자인 및 심미성",
      "description": "인테리어와의 조화, 색상 구성, 양면 활용 가능 여부",
      "importance": "medium",
      "examples": [
        "크림/그레이 색상",
        "양면 디자인(낮과 밤)",
        "인테리어 조화",
        "깔끔한 마감",
        "공간 확장성"
      ]
    },
    {
      "key": "material_sensory",
      "name": "소재 및 감각적 요소",
      "description": "피부에 닿는 촉감, 보행 시 소리(뽀드득), 초기 제품 냄새",
      "importance": "low",
      "examples": [
        "초기 화학 냄새",
        "뽀드득 소리",
        "끈적임 없는 촉감",
        "부드러운 표면",
        "피부 자극 없음"
      ]
    }
  ],
  "nasal_aspirator": [
    {
      "key": "suction_power",
      "name": "흡입력",
      "description": "콧물을 얼마나 효과적으로 제거할 수 있는지에 대한 성능 (강도, 지속성, 조절 가능 여부)",
      "importance": "high",
      "examples": [
        "끈적한 콧물 제거",
        "깊은 콧물 흡입",
        "흡입 강도 조절",
        "진공압 유지"
      ]
    },
    {
      "key": "cleaning_hygiene",
      "name": "세척 및 위생",
      "description": "사용 후 부품 분리 및 세척의 용이성과 콧물 역류 방지 구조 여부",
      "importance": "high",
      "examples": [
        "완전 분리 세척",
        "열탕 소독 가능",
        "역류 방지 구조",
        "세척솔 포함 여부"
      ]
    },
    {
      "key": "noise_vibration",
      "name": "소음 및 진동",
      "description": "작동 시 발생하는 소리의 크기와 기계의 진동 정도 (아이의 공포감 유발과 관련)",
      "importance": "high",
      "examples": [
        "저소음 모터",
        "드라이기 소리",
        "진동 세기",
        "아이가 놀라지 않음"
      ]
    },
    {
      "key": "portability_power_source",
      "name": "휴대성 및 전원 방식",
      "description": "제품의 크기, 무게 및 전원 공급 방식에 따른 이동 및 사용 편의성",
      "importance": "medium",
      "examples": [
        "건전지 교체형",
        "무선 사용",
        "컴팩트한 사이즈",
        "여행용 파우치"
      ]
    },
    {
      "key": "tip_quality_variety",
      "name": "팁 구성 및 재질",
      "description": "콧구멍에 닿는 팁의 소재, 크기, 모양의 다양성 및 안전성",
      "importance": "medium",
      "examples": [
        "말랑한 실리콘 팁",
        "다양한 사이즈(대/소)",
        "부드러운 마감",
        "성인용 팁 호환"
      ]
    },
    {
      "key": "child_friendly_features",
      "name": "아이 거부감 및 부가기능",
      "description": "아이가 기계에 대한 거부감을 줄일 수 있도록 돕는 기능 및 디자인",
      "importance": "medium",
      "examples": [
        "멜로디 재생 기능",
        "귀여운 디자인",
        "조명 기능",
        "부드러운 사용감"
      ]
    },
    {
      "key": "price_value",
      "name": "가격 및 가성비",
      "description": "제품 가격 대비 성능 만족도 및 고가 제품(예: 노시부)과의 비교 우위",
      "importance": "medium",
      "examples": [
        "3만원대 가성비",
        "고가 제품 대비 성능",
        "저렴한 유지비",
        "합리적인 가격"
      ]
    }
  ],
  "thermometer": [
    {
      "key": "accuracy_consistency",
      "name": "정확도 및 일관성",
      "description": "체온 측정 결과의 정밀함과 반복 측정 시 동일한 결과가 나오는 일관성 (병원 측정값과의 비교, 센서 기술 포함)",
      "importance": "high",
      "examples": [
        "병원급 정확도",
        "반복 측정 시 오차 없음",
        "예열 팁(Pre-warmed Tip)",
        "고막 온도 감지",
        "측정 위치 감지 센서"
      ]
    },
    {
      "key": "measurement_speed",
      "name": "측정 속도",
      "description": "체온 측정 버튼을 누른 후 결과가 나오기까지 걸리는 시간 (움직이는 아이를 위한 신속성)",
      "importance": "high",
      "examples": [
        "1초 측정",
        "즉각적인 반응 속도",
        "아이가 움직이기 전 완료",
        "연속 측정 가능"
      ]
    },
    {
      "key": "night_usability",
      "name": "야간 사용 편의성",
      "description": "어두운 밤이나 아이가 자는 동안 체온을 측정하기 위한 기능 (화면 밝기, 소음 조절)",
      "importance": "high",
      "examples": [
        "백라이트 LCD 화면",
        "야간 조명등",
        "무음/음소거 모드",
        "버튼 조작음",
        "수면 방해 최소화"
      ]
    },
    {
      "key": "hygiene_maintenance",
      "name": "위생 및 관리",
      "description": "교차 감염 방지를 위한 위생 관리 방식 및 유지보수 편의성 (필터 사용 여부 및 비용 포함)",
      "importance": "medium",
      "examples": [
        "일회용 렌즈 필터 교체",
        "필터 유지 비용",
        "필터 탈부착 편의성",
        "알콜 소독 가능 여부",
        "센서 오염 방지"
      ]
    },
    {
      "key": "smart_features",
      "name": "부가 기능",
      "description": "사용자 편의를 돕는 추가적인 스마트 기능 (기록 저장, 발열 알림 등)",
      "importance": "medium",
      "examples": [
        "메모리 기능(최근 기록 저장)",
        "연령별 발열 기준 설정(AgeSmart)",
        "발열 상태 색상 표시(LED)",
        "자동 전원 차단",
        "고열 경고음"
      ]
    },
    {
      "key": "ease_of_use",
      "name": "사용 편의성 및 디자인",
      "description": "제품의 조작 난이도, 그립감, 휴대성 등 물리적인 사용 경험",
      "importance": "medium",
      "examples": [
        "한 손 조작 그립감",
        "직관적인 버튼 구성",
        "휴대용 보관 케이스",
        "컴팩트한 사이즈",
        "건전지 교체 용이성"
      ]
    },
    {
      "key": "durability_reliability",
      "name": "내구성 및 신뢰성",
      "description": "제품의 수명, 고장 빈도, 브랜드에 대한 신뢰도 및 A/S 지원",
      "importance": "medium",
      "examples": [
        "잔고장 없음",
        "긴 사용 수명(10년 사용)",
        "낙하 충격 내구성",
        "브랜드 인지도(병원 사용)",
        "A/S 및 보상 판매 정책"
      ]
    }
  ]
} as const;
